config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users, only: :none do
    resources :u2f_registrations,
      only: [:index, :new, :create, :destroy]

    resources :u2f_authentications,
      only: [:new, :create]

    resources :pets, shallow: true
  end

  root to: 'pets#index'
end

app/models/pet.rb
# == Schema Information
#
# Table name: pets
#
#  id         :integer          not null, primary key
#  color      :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Pet < ActiveRecord::Base
  belongs_to :user
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = current_user.pets
  end

  def show
  end

  def new
    @pet  = Pet.new
    @user = current_user
  end

  def edit
  end

  def create
    @pet = current_user.pets.build(pet_params)

    if @pet.save
      redirect_to @pet, notice: 'Pet was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pet.update(pet_params)
      redirect_to @pet, notice: 'Pet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to user_pets_url(current_user), notice: 'Pet was successfully destroyed.'
  end

  private

  def set_pet
    @pet = current_user.pets.find_by(id: params[:id])
  end

  def pet_params
    params.require(:pet).permit(:color)
  end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_for [@user, @pet] do |f| %>
  <% if @pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>

      <ul>
      <% @pet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Editing Pet</h1>

<%= render 'form' %>

<%= link_to 'Show', @pet %> |
<%= link_to 'Back', user_pets_path(current_user) %>

app/views/pets/index.html.erb
<h1>Listing Pets</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pets.each do |pet| %>
      <tr>
        <td><%= pet.color %></td>
        <td><%= pet.user.email %></td>
        <td><%= link_to 'Show', pet %></td>
        <td><%= link_to 'Edit', edit_pet_path(pet) %></td>
        <td><%= link_to 'Destroy', pet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pet', new_user_pet_path(current_user) %>

app/views/pets/new.html.erb
<h1>New Pet</h1>

<%= render 'form' %>

<%= link_to 'Back', user_pets_path(current_user) %>

app/views/pets/show.html.erb
<p>
  <strong>Color:</strong>
  <%= @pet.color %>
</p>

<p>
  <strong>User:</strong>
  <%= @pet.user.email %>
</p>

<%= link_to 'Edit', edit_pet_path(@pet) %> |
<%= link_to 'Back', user_pets_path(current_user) %>